### PR TITLE
Update to the Current Windows WSL prework Guide.

### PR DESCRIPTION
**Pull request by michaeltreat**
Updated the current 201 Windows docs to make use of the new WSL feature. This allows them to work on a truely native POSIX terminal inside of Windows. There is a bit more to explain in the doc when compared to the Mac or Ubuntu prework, but that is because they will technically be using two File Systems, and because there is limited information out there as this is still relatively new. This doc offers a structured guide on how to go about developing while using this system. It is still in 1st draft, but I need some feedback before moving further here! Thanks!

### CODE REVIEW

**Comment by michaeltreat** [comment]
@brookr @bnates @samhamm

**Comment by michaeltreat** [comment]
Did another run through the doc to catch typos and grammar. Updated the linter file and changed the "update your profile" section to include the `wr` variable which is a shortcut to the Windows User's Root. Necessary because the `~` is referring to the Ubuntu root.

**Comment by bnates** [comment]
@michaeltreat this is awesome!  thanks for hooking this up!  💯 

we'll review during our 201 sync and provide feedback/approve once we've discussed

**Comment by mattwojo** [comment]
Hey guys - 
I was just looking over the latest Code Fellows offerings and where things are at in terms of supporting students who want to use Windows OS. I'm so pleased to WSL being incorporated into the 201 course. If you or any of the students who take this path encounter any problems, pain points, need for additional docs, etc, please let me know. I've recently started working with this team at Microsoft and they are very committed to doing whatever it takes to lure more devs back to Windows. What better way to do that than with the next generation at CF?! This could also be a cool little credential for a CF student to add to their merit badge sash if they request a feature that's implemented, or make a contribution to the (now opensource) docs, or find a way to improve WSL. 🥇 
On a more personal note, I completed my Code Fellows courses entirely on a PC dual-booting with Ubuntu. It had some challenges, but I believe it helped me to be more versatile with jumping between dev environments. (Which ended up coming in handy now that I'm at MS). 
~Matt Wojo (mattwoj@microsoft.com)

*Did notice one typo in the PR on line 11 of 01_preface: 
"Windows also offers a free [Ubuntu App](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6) from the Microsoft store called which hooks in perfectly with WSL."
You could probably just say: "You can install the Ubuntu App](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6) for free in the Microsoft store so that you can use the Ubuntu Terminal and run command line utilities including bash, ssh, git, apt, etc.
There are other Linux distros supported (Debian, SUSE, Kali, etc) but keeping things consistent by recommending the folks taking this route use Ubuntu seems wise to me. 
I'll read through again once this PR is approved and see whether I can find anything else to contribute.

**Comment by michaeltreat** [comment]
Thanks @mattwojo ! I also went through on Windows, then dual-booted into Ubuntu! 

I made this PR based off of some docs I wrote [Here](https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup). I'm continuing to update it and any feedback you have on it would be awesome! I will also update that line in the preface with your recommendation.

**Pull request merged**
